baseURL = "https://livewire.io/"
languageCode = "en-us"
title = "Livewire Labs"
theme = "etch"

[params]
  description = "livewire.io: Podcasting ▷ Forward"
  dark = "on"
  highlight = true
  custom_css = ["custom.css"]

[permalinks]
  posts = "/:slug/"
